package com.example.citizenmanagement.models;

public enum FeeMenuOptions {
    TRANG_CHU,
    THEM_KHOAN_THU_PHI,
    DANH_SACH_KHOAN_THU,

    CHI_TIET_KHOAN_THU,
    DANH_SACH_HO_KHAU_CAN_THU_PHI,
    DA_HOAN_THANH_DONG_PHI,
    CHUA_HOAN_THANH_DONG_PHI,
    FEE_PROFILE,
    THEM_KHOAN_THU_DOT,
    THEM_HO_KHAU_DOT,
    DANH_SACH_KHOAN_THU_DOT,
    CHI_TIET_KHOAN_THU_DOT,
    CHUA_HOAN_THANH_PHI_DOT,
    HOAN_THANH_PHI_DOT,
    THONG_TIN_HOA_DON,
    THONG_KE_DICH_VU,
    THONG_KE_QUAN_LY,
    THONG_KE_XE_MAY,
    THONG_KE_UNG_HO,
    THONG_KE_TIEN_UNG_HO,
    THONG_KE_TIEN_DIEN,
    THONG_KE_TIEN_NUOC,
    THONG_KE_TIEN_INTERNET

}
